// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maexsnqfhywddzfxqraw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZXhzbnFmaHl3ZGR6ZnhxcmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTUyNjksImV4cCI6MjA1Nzk3MTI2OX0.C0BHN_d2m_P2Yy9w5IMUAuVXVM8C0md-eLXBmNDMCBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);